# Generated by Django 3.2.7 on 2021-10-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='img_product',
            field=models.FileField(blank=True, upload_to='product_images'),
        ),
    ]
