# Generated by Django 3.2.7 on 2021-10-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_imageproduct_img_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='img_product',
            field=models.URLField(verbose_name='Путь до изображения'),
        ),
    ]
