# Generated by Django 3.2.7 on 2021-10-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_imageproduct_img_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='img_product',
            field=models.FileField(blank=True, null=True, upload_to='product_images', verbose_name='Файл'),
        ),
    ]
